"""empty message

Revision ID: 35387b148a1e
Revises: d61907e5b3f6
Create Date: 2024-11-01 15:26:45.227242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35387b148a1e'
down_revision = 'd61907e5b3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hold_date_check', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('hold_date_check')

    # ### end Alembic commands ###
