"""empty message

Revision ID: 382e1401136d
Revises: 8efc4dc730fc
Create Date: 2023-03-25 23:30:14.079894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382e1401136d'
down_revision = '8efc4dc730fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('mimetype', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('mimetype')
        batch_op.drop_column('name')
        batch_op.drop_column('scan')

    # ### end Alembic commands ###
