"""empty message

Revision ID: 3be8ef2660e6
Revises: a764a0eb7d24
Create Date: 2024-05-10 16:18:04.177788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be8ef2660e6'
down_revision = 'a764a0eb7d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gum_shade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('price', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('gum_shade')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
