"""empty message

Revision ID: 45e80a9c8f8c
Revises: 3be8ef2660e6
Create Date: 2024-05-20 10:42:20.542784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e80a9c8f8c'
down_revision = '3be8ef2660e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('production', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('production')
        batch_op.drop_column('shipping')

    # ### end Alembic commands ###
