"""empty message

Revision ID: 4e47359c3ae3
Revises: 540eef365bca
Create Date: 2024-03-16 23:59:49.536652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e47359c3ae3'
down_revision = '540eef365bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('update_date', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('update_date')
        batch_op.drop_column('creation_date')

    # ### end Alembic commands ###
