"""empty message

Revision ID: 540eef365bca
Revises: 7307bc09893d
Create Date: 2024-03-10 00:09:45.459831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540eef365bca'
down_revision = '7307bc09893d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teeth', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('product', sa.String(length=50), nullable=True))
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('product')
        batch_op.drop_column('teeth')

    # ### end Alembic commands ###
