"""empty message

Revision ID: 705a1a821a0d
Revises: f08da6420849
Create Date: 2024-09-19 14:58:18.675836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705a1a821a0d'
down_revision = 'f08da6420849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
