"""empty message

Revision ID: 7307bc09893d
Revises: 3133d8a37a2e
Create Date: 2024-03-09 23:39:38.913864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7307bc09893d'
down_revision = '3133d8a37a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'case', ['case_id'], ['id'])
        batch_op.drop_column('name')
        batch_op.drop_column('mimetype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('case_id')

    op.drop_table('case')
    # ### end Alembic commands ###
