"""empty message

Revision ID: 75d87fc534a8
Revises: 048274ef6d59
Create Date: 2024-04-23 00:18:33.546639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75d87fc534a8'
down_revision = '048274ef6d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('finish', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.alter_column('scan',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.alter_column('scan',
               existing_type=sa.String(length=255),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('finish')
        batch_op.drop_column('shade')

    # ### end Alembic commands ###
