"""empty message

Revision ID: 896082d4f699
Revises: 4e47359c3ae3
Create Date: 2024-03-17 01:22:21.852099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '896082d4f699'
down_revision = '4e47359c3ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('scan',
               existing_type=sa.TEXT(),
               type_=postgresql.BYTEA(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.alter_column('scan',
               existing_type=postgresql.BYTEA(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('scan_name')

    # ### end Alembic commands ###
