"""empty message

Revision ID: 8efc4dc730fc
Revises: e901e3cdb61f
Create Date: 2023-03-25 01:51:30.905869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efc4dc730fc'
down_revision = 'e901e3cdb61f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('fname', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('lname', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lname')
        batch_op.drop_column('fname')
        batch_op.drop_column('address')

    op.drop_table('scans')
    # ### end Alembic commands ###
