"""empty message

Revision ID: 93396dde096f
Revises: 35387b148a1e
Create Date: 2026-05-31 14:55:27.929141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93396dde096f'
down_revision = '35387b148a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('scanner_id', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctors', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('doctors')

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('scanner_id')
        batch_op.drop_column('doctor_name')

    # ### end Alembic commands ###
