"""empty message

Revision ID: 95042340eba5
Revises: 75d87fc534a8
Create Date: 2024-04-25 14:22:53.545418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95042340eba5'
down_revision = '75d87fc534a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
