"""empty message

Revision ID: c88f16c0eba3
Revises: 93396dde096f
Create Date: 2026-05-31 15:47:48.900954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88f16c0eba3'
down_revision = '93396dde096f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tooth_designations', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('tooth_designations')

    # ### end Alembic commands ###
