"""empty message

Revision ID: f4e294564938
Revises: dd625574c62a
Create Date: 2024-08-22 16:17:03.335172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e294564938'
down_revision = 'dd625574c62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('practice_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('office_phone', sa.String(length=25), nullable=False),
    sa.Column('mobile_phone', sa.String(length=25), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('find_us', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_request')
    # ### end Alembic commands ###
