//import react into the bundle
import React from "react";
import ReactDOM from "react-dom";

//include your index.scss file into the bundle
import "../styles/index.css";
import "../../../bootstrap.min.css"
import "../styles/slick-theme.css"
import "../styles/slick.css"
import "../styles/style.css"
import "../styles/linear.css"
import "../styles/_about.scss"
import "../styles/_banner.scss"
import "../styles/_benefit.scss"
import "../styles/_button.scss"
import "../styles/_call-to-action.scss"
import "../styles/_client.scss"
import "../styles/_contact.scss"
import "../styles/_faq.scss"
import "../styles/_feature.scss"
import "../styles/_food.scss"
import "../styles/_footer.scss"
import "../styles/_funfact.scss"
import "../styles/_googel-maps.scss"
import "../styles/_header.scss"
import "../styles/_main-slider.scss"
import "../styles/_marquee.scss"
import "../styles/_mega-menu.scss"
import "../styles/_menegement.scss"
import "../styles/_mobile-menu.scss"
import "../styles/_news.scss"
import "../styles/_offer.scss"
import "../styles/_pricing.scss"
import "../styles/_process.scss"
import "../styles/_progress.scss"
import "../styles/_reset.scss"
import "../styles/_projects.scss"
import "../styles/_room.scss"
import "../styles/_search-popup.scss"
import "../styles/_section-title.scss"
import "../styles/_services.scss"
import "../styles/_team.scss"
import "../styles/_testimonials.scss"
import "../styles/_what-we-do.scss"
import "../styles/_why-choose.scss"
import "../styles/_page-title.scss"
import "../fonts/fa-brands-400.ttf"
import "../fonts/fa-brands-400.woff"
import "../fonts/fa-brands-400.woff2"
import "../fonts/fa-duotone-900.ttf"
import "../fonts/fa-duotone-900.woff"
import "../fonts/fa-duotone-900.woff2"
import "../fonts/fa-light-300.ttf"
import "../fonts/fa-light-300.woff"
import "../fonts/fa-light-300.woff2"
import "../fonts/fa-regular-400.ttf"
import "../fonts/fa-regular-400.woff"
import "../fonts/fa-regular-400.woff2"
import "../fonts/fa-solid-900.ttf"
import "../fonts/fa-solid-900.woff"
import "../fonts/fa-solid-900.woff2"
import "../fonts/fa-thin-100.ttf"
import "../fonts/fa-thin-100.woff"
import "../fonts/fa-thin-100.woff2"
import "../fonts/Flaticon.eot"
import "../fonts/Flaticon.ttf"
import "../fonts/Flaticon.woff"
import "../fonts/Flaticon.woff2"
import "../fonts/linearicons-free.eot"
import "../fonts/linearicons-free.ttf"
import "../fonts/linearicons-free.woff"

import "../styles/jquery"
import "../styles/jquery.fancybox"
import "../styles/jquery-ui"
import "../styles/jquery.form.min"
import "../styles/jquery.validate.min"
import "../styles/script"
import "../styles/fontawesome.css"
import "../styles/progress-bar"
import "../styles/popper.min"
import "../styles/mixitup"
import "../styles/wow"
import "../styles/slick.min"
import "../styles/slick-animation.min"
import "../styles/appear"

import DomineBold from "../fonts/Domine Bold.ttf"

//import your own components
import Layout from "./layout";

//render your react application
ReactDOM.render(<Layout />, document.querySelector("#app"));
